"""Добавил таблицу places

Revision ID: 25e08626c67a
Revises: 30efb02d57b3
Create Date: 2022-04-25 17:36:37.942086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e08626c67a'
down_revision = '30efb02d57b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
