"""Добавил колонки lon и lat в таблицу places

Revision ID: 47d79fd0b3bb
Revises: 25e08626c67a
Create Date: 2022-04-27 19:59:04.783671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d79fd0b3bb'
down_revision = '25e08626c67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('lat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'lat')
    op.drop_column('places', 'lon')
    # ### end Alembic commands ###
