"""Убрать таблицу countries и ее связь с таблицей users

Revision ID: b6df821a4d85
Revises: 786fc56e839e
Create Date: 2022-04-16 19:33:59.981910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6df821a4d85'
down_revision = '786fc56e839e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_countries')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_to_countries',
    sa.Column('users', sa.INTEGER(), nullable=True),
    sa.Column('countries', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['countries'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    # ### end Alembic commands ###
